pipeline {
    agent any
    environment {
        BUILD_CONFIGURATION = 'Release'
        registry = ""
        dockerContainerName = 'wte'
        dockerImageName = 'wte-image'
    }
    stages {
        stage('Clean Container') {
            steps {
                script {
                    sh 'docker ps -f name=${dockerContainerName} -q | xargs --no-run-if-empty docker container stop'
                    sh 'docker container ls -a -f name=${dockerContainerName} -q | xargs -r docker container rm'
                    sh 'docker images -q --filter=reference=${dockerImageName} | xargs --no-run-if-empty docker rmi -f'
                }
            }
        }

        stage('Docker-Compose Start') {
            steps {
                script {
                    sh 'docker compose -f ./Docker/docker-compose-wte-site.yml up -d'
                }
            }
        }
    }
}
