pipeline {
    agent any
    environment {
        BUILD_CONFIGURATION = 'Release'
        registry = ""
        dockerContainerName = 'wte'
        dockerImageName = 'wte-image'
    }
    stages {
        stage('Build') {
            steps {
                sh 'dotnet restore'
                sh 'dotnet build --configuration $BUILD_CONFIGURATION'
                sh 'dotnet publish --configuration $BUILD_CONFIGURATION --output ./publish'
            }
        }

        stage('clean container') {
            steps {
                sh 'docker ps -f name=${dockerContainerName} -q | xargs --no-run-if-empty docker container stop'
                sh 'docker container ls -a -f name=${dockerContainerName} -q | xargs -r docker container rm'
                sh 'docker images -q --filter=reference=${dockerImageName} | xargs --no-run-if-empty docker rmi -f'
            }
        }

        stage('docker-compose start') {
            steps {
                sh 'docker compose -f ./docker/docker-compose-wte-site.yml up -d'
            }
        }
    }
}